// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKMPRsqWDus9nRpk1M8iucfOpLEMMV5g',
    appId: '1:956458941424:web:5f485c312de3bd76aa3b35',
    messagingSenderId: '956458941424',
    projectId: 'face-detector-494d8',
    authDomain: 'face-detector-494d8.firebaseapp.com',
    storageBucket: 'face-detector-494d8.appspot.com',
    measurementId: 'G-LF0K7FT3JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAysx8fFdHYb4OLEBnEAnDpaB8nja_WjCI',
    appId: '1:956458941424:android:38908b29e4df55a1aa3b35',
    messagingSenderId: '956458941424',
    projectId: 'face-detector-494d8',
    storageBucket: 'face-detector-494d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9vkD2CGJK5RbU0gNx0N_uqjpRoVdSE5g',
    appId: '1:956458941424:ios:83048c71046521e5aa3b35',
    messagingSenderId: '956458941424',
    projectId: 'face-detector-494d8',
    storageBucket: 'face-detector-494d8.appspot.com',
    iosClientId: '956458941424-gf5ihnv9mu48t55nh1ke4ul46h1g7h5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9vkD2CGJK5RbU0gNx0N_uqjpRoVdSE5g',
    appId: '1:956458941424:ios:83048c71046521e5aa3b35',
    messagingSenderId: '956458941424',
    projectId: 'face-detector-494d8',
    storageBucket: 'face-detector-494d8.appspot.com',
    iosClientId: '956458941424-gf5ihnv9mu48t55nh1ke4ul46h1g7h5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceDetector',
  );
}
